export const ACTOR_FILMS_REQUEST ='ACTOR_FILMS_REQUEST'
export const ACTOR_FILMS_SUCCESS ='ACTOR_FILMS_SUCCESS'
export const ACTOR_FILMS_FAILED = 'ACTOR_FILMS_FAILED'
export const ACTOR_REQUEST = 'ACTOR_REQUEST'
export const ACTOR_SUCCESS = 'ACTOR_SUCCESS'
export const ACTOR_FAILED = 'ACTOR_FAILED'



